import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
  weight: ['400', '500', '600', '700'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${inter.variable} ${styles.htmlFull}`}>
      <body
        className={styles.body}
        style={{ fontFamily: 'var(--font-inter), system-ui, sans-serif' }}
      >
        <div className={styles.full}>
          {children}
        </div>
      </body>
    </html>
  );
}
