import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${roboto.variable} font-sans antialiased h-full`}
        style={{ fontFamily: 'var(--font-roboto), Arial, Helvetica, sans-serif' }}
      >
        <div className="h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
